services:
  - type: web
    name: scandy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: RENDER
        value: "true"
